version: "3"

services:
  web:
    container_name: cutcat-web
    build: ./flask
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - redis
    env_file:
      - ./flask/.env
    volumes:
      - ./static:/usr/src/app/static

  redis:
    container_name: cutcat-session
    image: redis:alpine
    networks:
      - net

  rembg:
    container_name: cutcat-rembg
    build: ./rembg
    ports:
      - 8080:5000
    networks:
      - net

  screenpoint:
    container_name: cutcat-screenpoint
    build: ./screenpoint
    ports:
      - 8081:5000
    networks:
      - net

networks:
  net:
