version: '3'

services:
  
  web:
    container_name: catcat-web
    build: ./flask
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - redis
    env_file:
      - ./flask/.env

  redis:
    container_name: catcat-session
    image: redis:alpine
    networks:
      - net

  rembg:
    container_name: catcat-rembg
    build: ./rembg
    ports:
      - 8080:5000
    networks:
      - net
    env_file:
      - .env

networks:
  net: